name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
      - sandbox

jobs: 
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies 
        run: npm install

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-

      - name: Prepare environment variables
        run: |
          echo "export const environment = {" > environments/environment.prod.ts
          echo "  production: true," >> environments/environment.prod.ts
          echo "  API_URL: '$API_URL'" >> environments/environment.prod.ts
          echo "};" >> environments/environment.prod.ts
        env:
          API_URL: ${{ vars.API_URL }}

      - name: Build
        run: npm run build
        
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RIJKS_ART_GALLERY }}
          channelId: live
          projectId: rijks-art-gallery
